# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.2.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-json
          - id: check-yaml
          - id: check-toml
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: debug-statements
          - id: detect-private-key

    - repo: https://github.com/astral-sh/ruff-pre-commit
      # Ruff version.
      rev: v0.12.3
      hooks:
          # Run the linter.
          - id: ruff
            args: [--fix, --exit-non-zero-on-fix, --config=pyproject.toml]
          # Run the formatter.
          - id: ruff-format

    - repo: local
      hooks:
          - id: pyright
            name: pyright
            entry: uv run pyright
            files: ^src/
            language: system
            types: [python]

    - repo: https://github.com/PyCQA/bandit
      rev: "1.8.6" # Update me!
      hooks:
          - id: bandit
            args: ["-c", "pyproject.toml", "src/"]
            additional_dependencies: ["bandit[toml]"]

    - repo: https://github.com/pypa/pip-audit
      rev: v2.9.0
      hooks:
          - id: pip-audit
            args: [”--desc", "--fix"]
